-- ============================================
-- Parker Lewis — "Gradually, Then Suddenly"
-- Logical/economic arguments (paraphrased, attributed; never verbatim)
-- + a small set of verified, timeless facts
-- ============================================

-- New category for monetary / sound-money reasoning
insert into categories (slug, name_no, name_en, icon, description_no, description_en, sort_order) values
  ('monetary', 'Pengeteori & sound money', 'Monetary Theory & Sound Money', '🪙',
   'Logiske og økonomiske argumenter for Bitcoin som penger', 'Logical and economic arguments for Bitcoin as money', 8)
on conflict (slug) do nothing;

-- ============================================
-- Arguments
-- ============================================

insert into arguments
  (category_id, status, title_no, title_en, thesis_no, thesis_en, reasoning_no, reasoning_en,
   source_name, source_chapter, source_url, tags, fud_type, strength)
values

-- ---- Bitcoin Does Not Waste Energy ----
((select id from categories where slug='energy'), 'published',
 'Energi som sikrer bedre penger er ikke sløsing',
 'Energy that secures better money is not waste',
 'Å bruke energi på å sikre verdens mest pålitelige penger er en av de høyestverdige bruksområdene for energi, ikke sløsing.',
 'Spending energy to secure the most reliable form of money is among the highest-value uses of energy, not waste.',
 'Penger er det grunnleggende godet som lar et samfunn koordinere arbeid og ressurser. Når penger svikter, slik som ved hyperinflasjon, bryter forsyningskjeder og grunnleggende tjenester sammen. Energien som gjør et ikke-devaluerbart pengesystem troverdig, underbygger all økonomisk aktivitet nedstrøms.',
 'Money is the foundational good that lets a society coordinate labour and resources. When money fails, as in hyperinflation, supply chains and basic services break down. The energy that makes a non-debaseable money credible underwrites all downstream economic activity.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Does Not Waste Energy', 'https://unchained.com/blog/bitcoin-does-not-waste-energy',
 '{energy,monetary-policy,opportunity-cost}', 'energy', 'sound'),

((select id from categories where slug='energy'), 'published',
 'Asymmetrien i pengekollaps rettferdiggjør kostnaden',
 'The asymmetry of monetary collapse justifies the cost',
 'Selv om sannsynligheten for fiat-svikt er usikker, gjør den katastrofale nedsiden det rasjonelt å bruke energi på et alternativ.',
 'Even if the probability of fiat failure is uncertain, the catastrophic downside makes investing energy in an alternative rational.',
 'Historien viser gjentatte valutakollaps når penger kan trykkes ubegrenset. Kostnaden ved å sikre et fast-tilbud-alternativ er liten sammenlignet med tapet hvis det rådende systemet svikter. Det er en forsikring mot et høyrisiko-utfall, ikke bortkastet forbruk.',
 'History shows repeated currency collapses where money can be printed without limit. The cost of securing a fixed-supply alternative is small relative to the loss if the prevailing system fails. It is insurance against a high-impact outcome, not wasted consumption.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Does Not Waste Energy', 'https://unchained.com/blog/bitcoin-does-not-waste-energy',
 '{energy,risk,monetary-policy}', 'energy', 'sound'),

-- ---- Bitcoin is Not a Hedge ----
((select id from categories where slug='monetary'), 'published',
 'En erstatning, ikke en forsikring',
 'A replacement, not a hedge',
 'Bitcoin forstås best som en mulig etterfølger til dollaren, ikke som et sidespill mot den.',
 'Bitcoin is best understood as a candidate successor to the dollar, not a side bet against it.',
 'En hedge motvirker et usikkert utfall, men Bitcoins faste utstedelsesplan gjør de monetære egenskapene kjente snarere enn sannsynlighetsbaserte. Spørsmålet blir binært: enten holder taket på 21 millioner troverdig, eller ikke. Det er bestembart, ulikt et spekulativt veddemål.',
 'A hedge offsets an uncertain outcome, but the fixed issuance schedule of Bitcoin makes its monetary properties knowable rather than probabilistic. The question becomes binary: either the 21 million cap credibly holds, or it does not. That is determinable, unlike a speculative bet.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not a Hedge', 'https://unchained.com/blog/bitcoin-is-not-a-hedge',
 '{store-of-value,inflation,dollar}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Gjeldsbyrden tvinger frem mer pengetrykking',
 'The debt overhang forces more money printing',
 'Fordi kredittsystemet rommer langt mer dollargjeld enn det finnes dollar, presses myndighetene gjentatte ganger mot å skape mer valuta.',
 'Because the credit system holds far more dollar debt than there are dollars, authorities are repeatedly pushed toward creating more currency.',
 'Å la gjeld misligholdes i stor skala ville kollapset systemet. Derfor velges trykking fremfor opprydding, gang på gang. Det gjør fortsatt devaluering til den strukturelt mest sannsynlige veien.',
 'Allowing debt to default at scale would collapse the system, so printing is chosen over clearing, again and again. That makes continued debasement the structurally most likely path.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not a Hedge', 'https://unchained.com/blog/bitcoin-is-not-a-hedge',
 '{debt,monetary-policy,inflation}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Kortsiktige salg er likviditetshendelser',
 'Short-term selloffs are liquidity events',
 'At Bitcoin faller under en likviditetsskvis motbeviser ikke den langsiktige tesen.',
 'A Bitcoin drop during a liquidity squeeze does not refute the long-run thesis.',
 'Når dollarlikviditet strammes til, selger aktører det som er likvid for å betjene gjeld, inkludert Bitcoin. Et prisfall i en slik fase er en likviditetshendelse, ikke et tegn på sviktende verdi. De to må holdes adskilt.',
 'When dollar liquidity tightens, holders sell whatever is liquid to service debt, including Bitcoin. A price drop in that phase is a liquidity event, not a sign of failing value. The two must be kept distinct.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not a Hedge', 'https://unchained.com/blog/bitcoin-is-not-a-hedge',
 '{volatility,liquidity,store-of-value}', 'skepticism', 'plausible'),

-- ---- Bitcoin is the Great Definancialization ----
((select id from categories where slug='monetary'), 'published',
 'Styrt inflasjon tvinger alle til å bli investorer',
 'Engineered inflation forces everyone to invest',
 'En bevisst valutasvekkelse skyver vanlige folk ut av sparing og inn i finansprodukter bare for å holde tritt.',
 'A deliberate currency decline pushes ordinary people out of saving and into financial products just to keep pace.',
 'Når penger taper kjøpekraft hvert år, blir det å holde kontanter et garantert tap. Husholdninger tvinges til å ta risiko de ellers ikke ville tatt. Det blåser opp finanssektorens rolle på bekostning av trygg sparing.',
 'When money loses purchasing power every year, holding cash becomes a guaranteed loss. Households are forced to take on risk they would otherwise avoid. This inflates the role of the financial sector at the expense of safe saving.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is the Great Definancialization', 'https://unchained.com/blog/bitcoin-is-the-great-definancialization',
 '{savings,financialization,inflation}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Hardt penger gjenoppretter sparing',
 'Hard money restores saving',
 'Et fast tilbud belønner det å holde og bevare verdi, og snur refleksen om å bruke før pengene svekkes.',
 'A fixed supply rewards holding and preserving value, reversing the spend-before-it-devalues reflex.',
 'Sunn sparing bør være lavrisiko bevaring av formue. Når pengene ikke kan devalueres, kan folk igjen spare uten å måtte spekulere. Det sender renere prissignaler og kanaliserer kapital til produktiv bruk.',
 'Sound saving should be low-risk preservation of wealth. When money cannot be debased, people can save again without having to speculate. That sends cleaner price signals and routes capital to productive uses.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is the Great Definancialization', 'https://unchained.com/blog/bitcoin-is-the-great-definancialization',
 '{savings,time-preference,fixed-supply}', 'skepticism', 'sound'),

-- ---- Bitcoin is Antifragile ----
((select id from categories where slug='monetary'), 'published',
 'Ingen enkelt feilpunkt',
 'No single point of failure',
 'Distribuert kontroll betyr at det ikke finnes et knutepunkt å angripe eller stenge.',
 'Distributed control means there is no hub to attack or shut down.',
 'Fordi ingen part driver nettverket, finnes det ingen sentral brikke å presse eller slå ut. Styrken kommer nettopp fra fraværet av en kontrollør. Det gjør systemet motstandsdyktig mot både angrep og inngrep.',
 'Because no party runs the network, there is no central piece to coerce or knock out. Its strength comes precisely from the absence of a controller. That makes the system resilient to both attack and intervention.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Antifragile', 'https://unchained.com/blog/bitcoin-is-antifragile',
 '{decentralization,censorship-resistance,security}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Stress gjør nettverket sterkere',
 'Stress makes the network stronger',
 'Angrep, feil og volatilitet pleier å forbedre Bitcoin snarere enn bare å bli motstått.',
 'Attacks, bugs, and volatility tend to improve Bitcoin rather than merely being resisted.',
 'Et robust system tåler skade; et antiskjørt system lærer av den. Hver hendelse driver frem bedre sikkerhet, verktøy og praksis for oppbevaring. Over tid herdes nettverket av nettopp det som skulle knekke det.',
 'A robust system withstands damage; an antifragile one learns from it. Each incident drives better security, tooling, and custody practices. Over time the network is hardened by the very things meant to break it.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Antifragile', 'https://unchained.com/blog/bitcoin-is-antifragile',
 '{antifragility,security,resilience}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Volatilitet gjør nyttig arbeid',
 'Volatility does useful work',
 'Prissvingninger overfører informasjon og sprer eierskap til nye holdere.',
 'Price swings transmit information and spread ownership to new holders.',
 'Volatilitet er ikke bare støy; den flytter mynter fra tidlige til nye deltakere og brer eierskapet ut. Den trener også markedet i risikohåndtering. Slik er svingningene en del av modningsprosessen, ikke en defekt.',
 'Volatility is not just noise; it moves coins from early to new participants and broadens ownership. It also trains the market in risk management. In this way the swings are part of the maturing process, not a defect.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Antifragile', 'https://unchained.com/blog/bitcoin-is-antifragile',
 '{volatility,adoption,ownership}', 'skepticism', 'plausible'),

-- ---- Bitcoin is Common Sense ----
((select id from categories where slug='monetary'), 'published',
 'Gratis pengeskaping er en skjult overføring av andres arbeid',
 'Costless money creation is a hidden transfer of the labour of others',
 'Den som kan skape penger gratis, kan kreve andres produksjon uten å yte noe tilbake.',
 'Whoever can create money for free can claim the output of others without giving anything in return.',
 'I en liten økonomi ser man straks at én person som trykker penger gratis stjeler kjøpekraft fra resten. Den samme logikken gjelder sentralbanker, selv om samfunnet aksepterer det fra institusjoner. Mekanismen er den samme, bare i større skala.',
 'In a small economy it is immediately clear that one person printing money for free steals purchasing power from the rest. The same logic applies to central banks, even though society accepts it from institutions. The mechanism is identical, only at larger scale.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Common Sense', 'https://unchained.com/blog/bitcoin-is-common-sense',
 '{money-printing,purchasing-power,central-banks}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Trykking er ikke vekst',
 'Printing is not growth',
 'Nye pengeenheter skaper verken varer eller arbeidere; de omfordeler bare krav på den samme produksjonen.',
 'New money units create neither goods nor workers; they only redistribute claims on the same output.',
 'Mer penger uten mer produksjon betyr at hver enhet representerer en mindre andel av den reelle verdiskapingen. Resultatet er fortynning over tid, ikke velstand. Å forveksle pengemengde med rikdom er en grunnleggende feil.',
 'More money without more production means each unit represents a smaller share of real output. The result is dilution over time, not prosperity. Confusing money supply with wealth is a fundamental error.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Common Sense', 'https://unchained.com/blog/bitcoin-is-common-sense',
 '{money-printing,inflation,scarcity}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Cantillon-effekten',
 'The Cantillon effect',
 'De som er nærmest pengekranen vinner på bekostning av sparere og lønnsmottakere lenger ute i kjeden.',
 'Those nearest the money spigot gain at the expense of savers and wage-earners further down the chain.',
 'Nye penger når aktivaeiere og billige låntakere først, før prisene rekker å justere seg. Når effekten når vanlige folk, har kjøpekraften allerede falt. Dette er et strukturelt utfall, ikke ond vilje.',
 'New money reaches asset holders and cheap borrowers first, before prices adjust. By the time it reaches ordinary people, purchasing power has already fallen. This is a structural outcome, not malice.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Common Sense', 'https://unchained.com/blog/bitcoin-is-common-sense',
 '{cantillon-effect,inequality,monetary-policy}', 'skepticism', 'sound'),

-- ---- Bitcoin is a Rally Cry ----
((select id from categories where slug='monetary'), 'published',
 'Systemet var skjørt før sjokket',
 'The system was fragile before the shock',
 'Krisen stammer fra tiår med gjeldsoppbygging og undertrykte korreksjoner, ikke fra den utløsende hendelsen.',
 'The crisis stems from decades of leverage and suppressed corrections, not from the triggering event.',
 'Når markeder hindres i å rydde opp i dårlig gjeld, hoper ubalansene seg opp i det skjulte. Et sjokk avslører bare skjørheten som allerede var der. Intervensjoner utsetter problemet i stedet for å løse det.',
 'When markets are prevented from clearing bad debt, imbalances accumulate out of sight. A shock merely exposes the fragility that was already there. Interventions defer the problem rather than resolve it.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is a Rally Cry', 'https://unchained.com/blog/bitcoin-is-a-rally-cry',
 '{leverage,monetary-crisis,quantitative-easing}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Eskalerende inngrep viser tap av kontroll',
 'Escalating interventions show loss of control',
 'Når tiltak trappes opp fra rentekutt til ubegrenset oppkjøp på få dager, viser det at hvert tiltak er utilstrekkelig.',
 'When measures escalate from rate cuts to unlimited purchases within days, each one is proving insufficient.',
 'Behovet for stadig kraftigere inngrep avslører at myndighetene undervurderte omfanget. Det er et tegn på reaksjon, ikke styring. Et fast pengetilbud ville fjernet selve spaken som muliggjør slik eskalering.',
 'The need for ever-stronger intervention reveals that authorities misjudged the scale. It signals reaction, not control. A fixed money supply would remove the very lever that enables such escalation.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is a Rally Cry', 'https://unchained.com/blog/bitcoin-is-a-rally-cry',
 '{quantitative-easing,central-banks,fixed-supply}', 'skepticism', 'plausible'),

-- ---- Bitcoin Obsoletes All Other Money ----
((select id from categories where slug='monetary'), 'published',
 'Penger konvergerer, de fragmenterer ikke',
 'Money converges, it does not fragment',
 'Pengekonkurranse er ulik vanlig konkurranse: økonomier trekker mot ett dominerende medium.',
 'Monetary competition is unlike ordinary competition: economies gravitate toward one dominant medium.',
 'Pengers nytte kommer av hvor bredt de aksepteres, så verdien vokser med antall brukere. Å splitte på mange valutaer svekker prisinformasjonen alle er avhengige av. Derfor vinner det ledende nettverket gradvis terreng.',
 'The usefulness of money comes from how widely it is accepted, so value grows with the number of users. Splintering across many currencies degrades the price information everyone relies on. The leading network therefore gains ground over time.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Obsoletes All Other Money', 'https://unchained.com/blog/bitcoin-obsoletes-all-other-money',
 '{network-effects,monetary-convergence,sound-money}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Nettverkseffekter forsterker forspranget',
 'Network effects compound the lead',
 'Hver ny bruker øker antall mulige handelspar og skjerper prissignalene, så verdien vokser mer enn lineært.',
 'Each new user increases the possible trading pairs and sharpens price signals, so value grows more than linearly.',
 'Et ledende monetært nettverk blir mer nyttig jo flere som bruker det. Det trekker til seg ytterligere adopsjon, som igjen forsterker forspranget. Slik blir posisjonen stadig vanskeligere for rivaler å innhente.',
 'A leading monetary network becomes more useful the more people use it. That attracts further adoption, which again strengthens the lead. The position becomes ever harder for rivals to catch.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Obsoletes All Other Money', 'https://unchained.com/blog/bitcoin-obsoletes-all-other-money',
 '{network-effects,liquidity,adoption}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Tillitsløshet slår institusjonell tillit',
 'Trustlessness beats institutional trust',
 'Enhver rivaliserende valuta avhenger av en institusjon for å bevare egenskapene sine; Bitcoins regler håndheves av desentralisert konsensus.',
 'Every rival currency depends on an institution to preserve its properties; the rules of Bitcoin are enforced by decentralized consensus.',
 'Når ingen enkelt part kan endre tilbudet, blir knappheten troverdig uavhengig av politisk svikt. Brukere trenger ikke stole på en utsteder, bare verifisere reglene selv. Det er en sterkere garanti enn løfter fra en sentralbank.',
 'When no single party can change the supply, scarcity becomes credible regardless of political failure. Users need not trust an issuer, only verify the rules themselves. That is a stronger guarantee than promises from a central bank.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Obsoletes All Other Money', 'https://unchained.com/blog/bitcoin-obsoletes-all-other-money',
 '{trustlessness,decentralization,scarcity}', 'skepticism', 'sound'),

-- ---- Bitcoin is Not for Criminals ----
((select id from categories where slug='monetary'), 'published',
 'Nøytrale verktøy klandres ikke for misbruk',
 'Neutral tools are not blamed for misuse',
 'Veier, postsystemer, banker og kontanter brukes av både kriminelle og ærlige mennesker uten at vi kaller dem kriminelle.',
 'Roads, postal systems, banks, and cash all serve criminals and honest people alike without being called criminal.',
 'Å peke ut Bitcoin for den samme tosidige naturen er inkonsekvent. Et nøytralt verktøy defineres ikke av sin verste bruker. Den samme målestokken må gjelde for alle betalingsmidler.',
 'Singling out Bitcoin for the same dual-use nature is inconsistent. A neutral tool is not defined by its worst user. The same standard must apply to all means of payment.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not for Criminals', 'https://unchained.com/blog/bitcoin-is-not-for-criminals',
 '{crime,dual-use,censorship-resistance}', 'criminal', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Sensurresistens betyr at også uønskede transaksjoner går gjennom',
 'Censorship resistance means even unwanted transactions go through',
 'Hvis selv ulovlige transaksjoner ikke kan blokkeres på protokollnivå, beviser det ekte desentralisering.',
 'If even illicit transactions cannot be blocked at the protocol level, that proves genuine decentralization.',
 'I det øyeblikket én transaksjon kan stoppes, kan alle stoppes, og kjerneverdien forsvinner. Sensurresistens kan ikke være selektiv. Derfor er nettopp uangripeligheten et tegn på at systemet virker som tiltenkt.',
 'The moment one transaction can be blocked, all can be, and the core value disappears. Censorship resistance cannot be selective. So the very unstoppability is a sign the system works as intended.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not for Criminals', 'https://unchained.com/blog/bitcoin-is-not-for-criminals',
 '{censorship-resistance,decentralization,crime}', 'criminal', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Den kriminelle andelen krymper med adopsjon',
 'The criminal share shrinks with adoption',
 'Etter hvert som vanlige brukere strømmer til, faller andelen ulovlig bruk forholdsmessig.',
 'As mainstream users flow in, the share of illicit use falls proportionally.',
 'Ulovlig aktivitet utgjør allerede en liten del av fiat-bruk uten at fiat kalles kriminelle penger. De samme fordelene som trekker vanlige folk til Bitcoin, fortynner den kriminelle andelen. Over tid blir kriminelle en stadig mindre minoritet.',
 'Illicit activity already represents a small slice of fiat usage without fiat being called criminal money. The same advantages that draw ordinary people to Bitcoin dilute the criminal share. Over time criminals become an ever-smaller minority.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not for Criminals', 'https://unchained.com/blog/bitcoin-is-not-for-criminals',
 '{crime,adoption,illicit-use}', 'criminal', 'plausible'),

-- ---- Bitcoin Cannot Be Banned ----
((select id from categories where slug='monetary'), 'published',
 'Et forbud innrømmer at Bitcoin virker',
 'A ban concedes that Bitcoin works',
 'Å hevde at myndighetene vil forby Bitcoin innrømmer implisitt at det fungerer som penger.',
 'Arguing that governments will ban Bitcoin implicitly admits it works as money.',
 'Man forbyr ikke noe som er ubrukelig. Forbudsargumentet er ofte skeptikerens siste tilflukt. Det forutsetter nettopp den verdien det later som det avviser.',
 'You do not ban something useless. The ban argument is often the last refuge of the skeptic. It presupposes the very value it pretends to dismiss.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Cannot be Banned', 'https://unchained.com/blog/bitcoin-cannot-be-banned',
 '{regulation,ban,government}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Ingen sentral brikke å angripe',
 'No central chokepoint to attack',
 'Med noder og nøkler spredt over jurisdiksjoner finnes det ikke ett knutepunkt å slå ut.',
 'With nodes and keys spread across jurisdictions, there is no single chokepoint to knock out.',
 'Å stoppe åpen kildekode og signerte kringkastinger over hele verden overgår enhver stats håndhevingsevne. Et forbud i ett land flytter bare aktiviteten til et annet. Desentraliseringen gjør håndheving praktisk umulig.',
 'Stopping open-source software and signed broadcasts worldwide exceeds the enforcement reach of any state. A ban in one country merely shifts activity to another. Decentralization makes enforcement practically impossible.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Cannot be Banned', 'https://unchained.com/blog/bitcoin-cannot-be-banned',
 '{decentralization,ban,regulation}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Jurisdiksjonelt fangenes dilemma',
 'A jurisdictional prisoners dilemma',
 'Et land som forbyr Bitcoin skyver kapital mot mer tillatende rivaler.',
 'A country that bans Bitcoin pushes capital toward more permissive rivals.',
 'Fordi forbud straffer den som forbyr, blir koordinerte og varige forbud strukturelt ustabile. Hver stat har insentiv til å avvike for å tiltrekke kapital. Derfor er et globalt, vellykket forbud lite sannsynlig.',
 'Because a ban penalizes the banner, coordinated and lasting bans are structurally unstable. Each state has an incentive to defect to attract capital. A global, successful ban is therefore unlikely.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Cannot be Banned', 'https://unchained.com/blog/bitcoin-cannot-be-banned',
 '{game-theory,regulation,ban}', 'skepticism', 'plausible'),

-- ---- Bitcoin is Not a Pyramid Scheme ----
((select id from categories where slug='monetary'), 'published',
 'Mangler strukturen til et pyramidespill',
 'Lacks the structure of a pyramid scheme',
 'Pyramidespill krever et selskap, rekrutteringsbaserte utbetalinger og varelager som selges til deltakerne; Bitcoin har ingen av delene.',
 'Pyramid schemes require a company, recruitment-based payouts, and inventory sold to participants; Bitcoin has none of these.',
 'Bitcoins verdi hviler på monetære egenskaper, ikke på å verve nye medlemmer. Det finnes ingen sentral aktør som tar inn innskudd eller lover avkastning. Uten disse elementene faller selve definisjonen bort.',
 'The value of Bitcoin rests on monetary properties, not on enrolling new members. There is no central operator taking deposits or promising returns. Without these elements the definition simply does not apply.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not a Pyramid Scheme', 'https://unchained.com/blog/bitcoin-is-not-a-pyramid-scheme',
 '{ponzi,pyramid-scheme,fixed-supply}', 'ponzi', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Adopsjon fortynner eierskap, ikke beriker innsidere',
 'Adoption dilutes ownership, it does not enrich insiders',
 'Når flere holder Bitcoin, fordeles den faste mengden tynnere per person, det motsatte av et pyramidespill.',
 'As more people hold Bitcoin, the fixed quantity spreads thinner per person, the inverse of a pyramid scheme.',
 'I et pyramidespill tjener tidlige deltakere på de seneres bekostning. Her er det faste tilbudet upåvirket av hvem som kommer inn når. Verdien følger av knapphet og etterspørsel, ikke av en rekrutteringskjede.',
 'In a pyramid scheme early participants profit at the expense of later ones. Here the fixed supply is unaffected by who enters when. Value follows from scarcity and demand, not a recruitment chain.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not a Pyramid Scheme', 'https://unchained.com/blog/bitcoin-is-not-a-pyramid-scheme',
 '{ponzi,scarcity,ownership}', 'ponzi', 'sound'),

-- ---- Bitcoin is Not Backed by Nothing ----
((select id from categories where slug='monetary'), 'published',
 'Pengers verdi kommer av egenskaper, ikke dekret',
 'The value of money comes from properties, not decree',
 'Knapphet, holdbarhet, delelighet, ombyttelighet og portabilitet gir et medium monetær verdi, ikke statlig påbud.',
 'Scarcity, durability, divisibility, fungibility, and portability give a medium monetary value, not government decree.',
 'Dollaren lånte først troverdighet fra gull og fjernet siden ankeret. Penger får ikke verdi fra militærmakt eller skatter, men fra egenskapene som gjør dem brukbare. Bitcoin scorer høyt på nettopp disse egenskapene.',
 'The dollar first borrowed credibility from gold, then removed the anchor. Money does not get value from military power or taxes, but from the properties that make it usable. Bitcoin scores highly on exactly these properties.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not Backed by Nothing', 'https://unchained.com/blog/bitcoin-is-not-backed-by-nothing',
 '{intrinsic-value,monetary-properties,gold}', 'useless', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Dollaren er dekket av gjeldsdrevet etterspørsel',
 'The dollar is backed by debt-driven demand',
 'Etterspørselen etter dollar kommer i stor grad fra behovet for å betjene dollargjeld.',
 'Demand for dollars comes largely from the need to service dollar debt.',
 'Enorme gjeldsforpliktelser mot langt færre faktiske dollar skaper en kunstig, vedvarende etterspørsel. Systemet krever stadig ny kreditt og pengeutvidelse for å unngå kollaps. Det er en annen form for dekning enn folk tror.',
 'Vast debt obligations against far fewer actual dollars create artificial, persistent demand. The system requires continual new credit and money expansion to avoid collapse. That is a different kind of backing than people assume.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not Backed by Nothing', 'https://unchained.com/blog/bitcoin-is-not-backed-by-nothing',
 '{fiat,debt,monetary-policy}', 'useless', 'sound'),

-- ---- Bitcoin, Not Blockchain ----
((select id from categories where slug='monetary'), 'published',
 'Mynt og blokkjede er uatskillelige',
 'Coin and blockchain are inseparable',
 'Hovedboken trenger en innebygd mynt for å finansiere sikkerheten, og mynten trenger hovedbokens uforanderlighet for å fungere som penger.',
 'The ledger needs a native coin to fund its security, and the coin needs the immutability of the ledger to work as money.',
 'Fjerner du mynten, forsvinner insentivet som betaler for sikkerheten. Fjerner du hovedboken, mister mynten egenskapene som gjør den til penger. Ideen om blokkjede uten mynt misforstår hvordan systemet henger sammen.',
 'Remove the coin and the incentive that pays for security disappears. Remove the ledger and the coin loses the properties that make it money. The idea of blockchain without a coin misunderstands how the system holds together.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin, Not Blockchain', 'https://unchained.com/blog/bitcoin-not-blockchain',
 '{blockchain,proof-of-work,native-currency}', 'useless', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Proof-of-work-kostnaden er sikkerheten',
 'The proof-of-work cost is the security',
 'At utvinning krever reell energibruk gir aktørene noe å tape, og det er nettopp dette som beskytter nettverket.',
 'That mining requires real energy gives participants something to lose, and that is exactly what protects the network.',
 'Uten en håndfast kostnad ville det ikke vært noen barriere mot angrep. Energien er ikke en bivirkning, men selve forsvarsmekanismen. Den gjør juks økonomisk irrasjonelt i stor skala.',
 'Without a tangible cost there would be no barrier to attack. The energy is not a side effect but the defence mechanism itself. It makes cheating economically irrational at scale.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin, Not Blockchain', 'https://unchained.com/blog/bitcoin-not-blockchain',
 '{proof-of-work,security,mining}', 'useless', 'sound'),

-- ---- Bitcoin Fixes This ----
((select id from categories where slug='monetary'), 'published',
 'Skjønnsmessig pengestyring skaper skjørhet',
 'Discretionary money management manufactures fragility',
 'Å manipulere pengemengden korrumperer prissignalene markeder er avhengige av, og hoper opp skjult risiko.',
 'Manipulating the money supply corrupts the price signals markets rely on and accumulates hidden risk.',
 'Når myndigheter justerer pengemengden etter eget skjønn, sendes feil informasjon gjennom systemet. Ressurser feilallokeres, og ubalanser bygger seg opp uoppdaget. Stabiliteten man sikter mot, undergraves over tid.',
 'When authorities adjust the money supply at their discretion, wrong information flows through the system. Resources are misallocated and imbalances build up undetected. The stability being aimed for is undermined over time.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Fixes This', 'https://unchained.com/blog/bitcoin-fixes-this',
 '{monetary-policy,central-banks,price-signals}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Gjeld kan ikke kurere gjeld',
 'Debt cannot cure debt',
 'Å møte for mye gjeld med enda mer gjeld utsetter ubalansen i stedet for å løse den.',
 'Meeting too much debt with even more debt defers the imbalance rather than resolving it.',
 'Etter en kredittboble er valget å la systemet rydde opp eller trykke for å forsvare gjelden. Å velge det siste behandler symptomet, ikke årsaken. Problemet skyves dermed videre, ofte i større form.',
 'After a credit bubble the choice is to let the system clear or to print to defend the debt. Choosing the latter treats the symptom, not the cause. The problem is pushed forward, often in larger form.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Fixes This', 'https://unchained.com/blog/bitcoin-fixes-this',
 '{debt,leverage,quantitative-easing}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Distribuert konsensus slår sentral planlegging',
 'Distributed consensus beats central planning',
 'Ingen liten komité har nok informasjon til å styre en kompleks økonomi (Hayeks kunnskapsproblem).',
 'No small committee has enough information to steer a complex economy (the Hayek knowledge problem).',
 'Kunnskapen som trengs er spredt blant millioner av aktører og kan ikke samles på ett bord. Bitcoin erstatter sentral beslutning med regelbasert konsensus. Reglene er kjente på forhånd og kan ikke endres etter forgodtbefinnende.',
 'The knowledge needed is dispersed among millions of actors and cannot be gathered in one place. Bitcoin replaces central decision-making with rule-based consensus. The rules are known in advance and cannot be changed at will.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Fixes This', 'https://unchained.com/blog/bitcoin-fixes-this',
 '{hayek,central-banks,decentralization}', 'skepticism', 'sound'),

-- ---- Bitcoin is Not Too Slow ----
((select id from categories where slug='monetary'), 'published',
 'Knapphet er gjennombruddet, gjennomstrømning er sekundært',
 'Scarcity is the breakthrough, throughput is secondary',
 'Bitcoins nyvinning er beviselig endelige digitale penger; transaksjonskapasitet er et ingeniørproblem som løses i lag.',
 'The Bitcoin innovation is provably finite digital money; transaction capacity is an engineering problem solved in layers.',
 'Å skape ekte digital knapphet var et sprang fra null til én. Hastighet er et sprang fra én til mange, som kan løses uten å røre grunnlaget. Å fokusere på gjennomstrømning bommer på hva som faktisk var vanskelig.',
 'Creating genuine digital scarcity was a leap from zero to one. Speed is a leap from one to many, solvable without touching the base. Focusing on throughput misses what was actually hard.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not Too Slow', 'https://unchained.com/blog/bitcoin-is-not-too-slow',
 '{scalability,settlement-layer,lightning-network}', 'useless', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Feil sammenligningsgrunnlag',
 'The wrong benchmark',
 'Bitcoin er et oppgjørs- og basispengelag, sammenlignbart med en sentralbank, ikke med en betalingsformidler.',
 'Bitcoin is a settlement and base-money layer, comparable to a central bank, not a payments processor.',
 'Å sammenligne basislaget med Visa er en kategorifeil. Sentralbankoppgjør skjer heller ikke på sekunder. Betalinger i butikk håndteres av lag oppå, slik som Lightning.',
 'Comparing the base layer to Visa is a category error. Central bank settlement does not happen in seconds either. Retail payments are handled by layers on top, such as Lightning.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin is Not Too Slow', 'https://unchained.com/blog/bitcoin-is-not-too-slow',
 '{settlement-layer,lightning-network,scalability}', 'useless', 'sound'),

-- ---- Bitcoin is Not Too Volatile ----
((select id from categories where slug='monetary'), 'published',
 'Volatilitet og verdibevaring er ulike akser',
 'Volatility and store-of-value are different axes',
 'En stabil pris er ikke det samme som god verdibevaring; dollaren er prisstabil, men taper kjøpekraft via inflasjon.',
 'A stable price is not the same as good store-of-value; the dollar is price-stable yet loses purchasing power via inflation.',
 'Kritikere blander sammen kortsiktige svingninger og langsiktig verdibevaring. Et volatilt aktivum kan bevare formue godt over riktig tidshorisont. De to egenskapene må vurderes hver for seg.',
 'Critics conflate short-term swings with long-term wealth preservation. A volatile asset can preserve wealth well over the right horizon. The two properties must be assessed separately.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Is Not Too Volatile', 'https://unchained.com/blog/bitcoin-is-not-too-volatile',
 '{volatility,store-of-value,inflation}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Fast tilbud gjør at etterspørsel uttrykkes i pris',
 'Fixed supply means demand expresses itself in price',
 'Når tilbudet er uelastisk, har økende etterspørsel ingen annen vei enn prisen.',
 'When supply is inelastic, rising demand has nowhere to go but price.',
 'Et fast tilbud kan ikke utvides for å møte etterspørsel, slik tradisjonelle varer kan. Derfor blir volatilitet selve mekanismen som kommuniserer adopsjonsfremgang. Svingningene er en konsekvens av designet, ikke en feil.',
 'A fixed supply cannot expand to meet demand the way ordinary goods can. So volatility becomes the very mechanism that communicates adoption progress. The swings are a consequence of the design, not a flaw.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Is Not Too Volatile', 'https://unchained.com/blog/bitcoin-is-not-too-volatile',
 '{volatility,fixed-supply,price-discovery}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Volatiliteten avtar med modning',
 'Volatility decays with maturity',
 'Etter hvert som adopsjonen nærmer seg metning, blir hver ny gruppe en mindre andel av totalen, og svingningene krymper.',
 'As adoption approaches saturation, each new cohort is a smaller share of the total, and the swings shrink.',
 'Tidlig i adopsjonen flytter små kapitalstrømmer prisen mye. Når brukermassen vokser, blir nettverket vanskeligere å rikke. Derfor bør volatiliteten falle over tid, ikke vedvare.',
 'Early in adoption, small capital flows move the price a lot. As the user base grows, the network becomes harder to move. So volatility should fall over time, not persist.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Is Not Too Volatile', 'https://unchained.com/blog/bitcoin-is-not-too-volatile',
 '{volatility,adoption,maturity}', 'skepticism', 'plausible'),

-- ---- Bitcoin Cannot Be Copied ----
((select id from categories where slug='monetary'), 'published',
 'Penger konvergerer til én standard',
 'Money converges to one standard',
 'En rasjonell aktør velger valutaen en milliard mennesker aksepterer fremfor en som en million aksepterer.',
 'A rational actor takes the currency a billion people accept over one a million accept.',
 'Akkurat som folk velger ett oppbevaringssted for formue fremfor mange, konsoliderer monetære nettverk seg. Likviditet og aksept trekker mot ett standardvalg. Det gjør det rasjonelt å samle seg om det ledende nettverket.',
 'Just as people pick one store of wealth over many, monetary networks consolidate. Liquidity and acceptance pull toward a single standard. That makes converging on the leading network rational.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Cannot Be Copied', 'https://unchained.com/blog/bitcoin-cant-be-copied',
 '{altcoins,network-effects,monetary-convergence}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Desentralisering, ikke funksjoner, skaper verdi',
 'Decentralization, not features, creates value',
 'Bitcoins verdi kommer av troverdig håndhevet knapphet gjennom desentralisering, ikke av tekniske finesser.',
 'The value of Bitcoin comes from credibly enforced scarcity through decentralization, not technical features.',
 'En klon kan kopiere koden, men ikke nettverkseffektene og likviditeten som er bygd opp over tid. Raskere eller mer programmerbare alternativer løser et ingeniørproblem, ikke det monetære. Derfor er innhenting økonomisk irrasjonell.',
 'A clone can copy the code, but not the network effects and liquidity built over time. Faster or more programmable alternatives address an engineering problem, not the monetary one. Catching up is therefore economically irrational.',
 'Parker Lewis — Gradually, Then Suddenly', 'Bitcoin Cannot Be Copied', 'https://unchained.com/blog/bitcoin-cant-be-copied',
 '{altcoins,decentralization,network-effects}', 'skepticism', 'sound'),

-- ---- Enders Game ----
((select id from categories where slug='monetary'), 'published',
 'Å undertrykke volatilitet bygger skjult risiko',
 'Suppressing volatility builds hidden risk',
 'Å møte hver nedtur med rentekutt og likviditet hindret markeder i å rydde opp i dårlig gjeld.',
 'Meeting every downturn with rate cuts and liquidity prevented markets from clearing bad debt.',
 'Den såkalte store roen var egentlig en stor undertrykkelse, der kreditt fikk vokse forbi reell produksjon. Hver redning fjernet en korreksjon og la til mer risiko. Risikoen forsvant ikke, den ble bare skjøvet fremover og forstørret.',
 'The so-called Great Moderation was really a great suppression, letting credit outgrow real output. Each rescue removed a correction and added more risk. The risk did not disappear, it was merely pushed forward and enlarged.',
 'Parker Lewis — Gradually, Then Suddenly', 'Enders Game', 'https://unchained.com/blog/enders-game',
 '{federal-reserve,leverage,quantitative-easing}', 'other', 'sound'),

((select id from categories where slug='monetary'), 'published',
 '2008 var en dollarmangel oppå en gjeldspyramide',
 '2008 was a dollar shortage atop a debt pyramid',
 'Krisen oppsto fordi det fantes langt flere dollarforpliktelser enn faktiske dollar i et flerlags gjeldssystem.',
 'The crisis arose because there were far more dollar obligations than actual dollars in a multi-layered debt system.',
 'Da tilliten brast, krevde alle dollar samtidig, og det tvang frem kaskader av tvangssalg. Problemet var ikke bare subprime, men selve gjeldspyramiden. Det forklarer hvorfor inngrepene måtte bli så store.',
 'When confidence broke, everyone demanded dollars at once, forcing cascading fire-sales. The problem was not just subprime, but the debt pyramid itself. That explains why the interventions had to be so large.',
 'Parker Lewis — Gradually, Then Suddenly', 'Enders Game', 'https://unchained.com/blog/enders-game',
 '{2008-crisis,leverage,debt}', 'other', 'sound'),

-- ---- Gradually, Then Suddenly (intro) ----
((select id from categories where slug='monetary'), 'published',
 'Forstå penger før du dømmer Bitcoin',
 'Understand money before judging Bitcoin',
 'Å forstå Bitcoin krever først å forstå hva penger er, og hvorfor noen verdilagre utkonkurrerer andre.',
 'Understanding Bitcoin requires first understanding what money is, and why some stores of value outcompete others.',
 'Penger er ikke vilkårlig tro, men oppstår fra de komparative fordelene til konkurrerende verdilagre. Uten dette rammeverket virker Bitcoin uforståelig. Med det blir adopsjonsbanen logisk.',
 'Money is not arbitrary belief, but emerges from the comparative advantages of competing stores of value. Without this framework Bitcoin seems incomprehensible. With it, the adoption path becomes logical.',
 'Parker Lewis — Gradually, Then Suddenly', 'Gradually, Then Suddenly (Introduction)', 'https://unchained.com/blog/dollar-crisis-to-bitcoin',
 '{sound-money,monetary-history,fiat}', 'skepticism', 'sound'),

((select id from categories where slug='monetary'), 'published',
 'Taket på 21 millioner er troverdig politikk, ikke bare kode',
 'The 21 million cap is credible policy, not just code',
 'Det faste tilbudet håndheves av distribuerte økonomiske insentiver, ikke bare av programlinjer.',
 'The fixed supply is enforced by distributed economic incentives, not merely by lines of code.',
 'Når mange rasjonelle aktører frivillig adopterer beviselig knappe penger, vil de ikke kollektivt velge å devaluere dem. Det er det motsatte av sentralt styrt valuta. Troverdigheten kommer fra insentivene som binder alle deltakere.',
 'When many rational actors voluntarily adopt verifiably scarce money, they will not collectively choose to debase it. That is the opposite of centrally controlled currency. The credibility comes from the incentives binding all participants.',
 'Parker Lewis — Gradually, Then Suddenly', 'Gradually, Then Suddenly (Introduction)', 'https://unchained.com/blog/dollar-crisis-to-bitcoin',
 '{fixed-supply,incentives,sound-money}', 'skepticism', 'sound');

-- ============================================
-- Verified facts (timeless or current-verified)
-- ============================================

insert into facts
  (category_id, status, claim_no, claim_en, reality_no, reality_en,
   source_name, source_url, source_date, batten_tip_no, batten_tip_en, tags, confidence)
values

((select id from categories where slug='myths'), 'published',
 'Bitcoin brukes hovedsakelig av kriminelle',
 'Bitcoin is mainly used by criminals',
 'Ulovlig aktivitet utgjør under 1 % av alt kryptovolum (Chainalysis 2025), og stablecoins, ikke Bitcoin, står nå for omtrent 84 % av det ulovlige volumet.',
 'Illicit activity makes up under 1% of all crypto transaction volume (Chainalysis 2025), and stablecoins, not Bitcoin, now account for roughly 84% of illicit volume.',
 'Chainalysis Crypto Crime Report', 'https://www.chainalysis.com/blog/2025-crypto-crime-report-introduction/', '2025-01-01',
 'Spør gjerne: visste du at uavhengige kjedeanalyse-firmaer måler den ulovlige andelen til under én prosent?',
 'You might ask: are you aware that independent chain-analysis firms measure the illicit share at under one percent?',
 '{crime,chainalysis,illicit-use,stablecoins}', 'high'),

((select id from categories where slug='myths'), 'published',
 'Myndighetene kan bare forby Bitcoin',
 'Governments can simply ban Bitcoin',
 'Forbud har en svak historikk: USAs gullbeslag i 1933 (Executive Order 6102) knuste ikke gullets verdi og ble opphevet da privat gulleierskap igjen ble lovlig i 1974. Indias 2018-bankforbud mot krypto ble opphevet av landets høyesterett i 2020.',
 'Prohibition has a poor track record: the 1933 U.S. gold confiscation (Executive Order 6102) did not destroy the value of gold and was reversed when private gold ownership became legal again in 1974. The 2018 Indian banking ban on crypto was struck down by its Supreme Court in 2020.',
 'U.S. National Archives (EO 6102); Supreme Court of India (IAMAI v. RBI, 2020)', null, '2020-03-04',
 'Spør gjerne: hvis Bitcoin var verdiløst, hvorfor skulle noen bry seg om å forby det?',
 'You might ask: if Bitcoin were worthless, why would anyone bother banning it?',
 '{ban,regulation,gold,history,india}', 'high');
